server:
  port: 8080
  servlet:
    session:
      timeout: 10m  # 设置会话有效时长，不写默认30分钟，最低1分钟,如果低于1分钟默认1分钟

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.1.47/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  session:
    store-type: redis # 采用redis存session
  redis:
    port: 6379 # redis端口号

mengxuegu:
  security:
    authentication:
      loginPage: /login/page # 响应登录界面
      loginProcessingUrl: /login/form #响应提交按钮
      codeImage: /code/image # 验证码
      usernameParameter: name
      passwordParameter: pwd
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT # JSON/REDIRECT
      mobilePage: /mobile/page # 登录手机验证码页面
      codeMobile: /code/mobile # 发送验证码
      mobileForm: /mobile/form  # 提交手机验证码页面的登录按钮
      tokenValiditySeconds: 604800 # 记住我的有效时长