server:
  port: 8080

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存

mengxuegu:
  security:
    authentication:
      loginPage: /login/page # 响应登录界面
      loginProcessingUrl: /login/form #响应提交按钮
      usernameParameter: name
      passwordParameter: pwd
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT # JSON/REDIRECT
