server:
  port: 8080

spring:
  thymeleaf:
    cache: false #关闭thymeleaf缓存
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.1.47/user_center?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://127.0.0.1:3306/security?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root

mengxuegu:
  security:
    authentication:
      loginPage: /login/page # 响应登录界面
      loginProcessingUrl: /login/form #响应提交按钮
      loginImage: /code/image # 验证码
      usernameParameter: name
      passwordParameter: pwd
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT # JSON/REDIRECT
      loginMobile: /mobile/page # 登录手机验证码页面
      codeMobile: /code/mobile # 发送验证码
      loginForm: /login/form  # 提交手机验证码页面的登录按钮